### ISSUE TITLE
Test Current Build (when it works)

### ISSUE THREAD

**Issue by ItsNotGoop** [cozycode-us/capstone#30]

**Comment by minetter** [comment]
Current build error:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "cozycode.capstone.parking.spaces.ParkingSpace.getType()" because "space" is null
	at cozycode.capstone.parking.ParkingGarage.assignSpace(ParkingGarage.java:75)
	at cozycode.capstone.Main.main(Main.java:54)

Error occurs after all user inputs are made

**Comment by minetter** [comment]
New build does not return an error, rather it loops the inputs and doesn't complete the actions requested

**Comment by minetter** [comment]
attempting to leave a l=parking space returns this error after employee id is inputted
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "cozycode.capstone.parking.car.Car.getId()" because the return value of "cozycode.capstone.parking.spaces.ParkingSpace.getCar()" is null
	at cozycode.capstone.parking.ParkingGarage.leaveSpace(ParkingGarage.java:90)
	at cozycode.capstone.Main.main(Main.java:67)

**Comment by minetter** [comment]
new build:


![Image](https://github.com/cozycode-us/capstone/assets/71468091/8348d045-c16d-49bf-a23c-992728134a94)

**Comment by minetter** [comment]
AS OF 5/21
Works: assignment/leave

Not intended: can assign all spots to one employee ID (no spot limit per id)

current error: occurs when there are no more parking spaces
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "cozycode.capstone.parking.car.Car.getMake()" because the return value of "cozycode.capstone.ticketing.Ticket.getCar()" is null
	at cozycode.capstone.ticketing.Display$FindSpotActionListener.actionPerformed(Display.java:167)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
